export const songs = [
  'A primera Vista',
  'Muchacha',
  'Hacer un puente',
  'Ella',
  'De Música Ligera',
  'Flaca',
  'Promesas sobre el Videt',
  'Mil horas',
  'Tan Solo',
  'Lamento Boliviano',
  'Persiana Americana',
  'Crimen',
  'A rodar',
  '11 Y 6',
  'Fue amor',
  'Juntos a la par',
  'Laura no está',
  'Sin documentos',
  'Seguir viviendo sin tu amor',
  'Mujer amante',
  'Chau',
  'Putita',
  'Pupilas lejanas',
  'Desconfiío',
  'No podrás',
  'Trátame suavemente',
  'Seminare',
  'A veces',
  'Radios',
  'Ahora te puedes marchar',
  'Suave',
  'La flaca',
  'Bésame',
  'La bamba',
  'Que nadie sepa mi sufrir',
  'Labios Compartidos',
  'Besos en guerra',
  'Ciega Sorda Muda',
  'Deseo de cosas imposibles',
  'A puro Dolor',
  'Mi historia entre tus dedos',
  'Un siglo sin ti',
  'Todo Cambió',
  'Solamente Tú',
  'Corazón Hambriento',
  'Cha Cha cha',
  'Ojos Marrones',
  'Garganta con Arena',
  'Cambalache',
  'Balada para un loco',
  'Por lo que yo te quiero',
  'Soy cordobés',
  'Que ironía',
  'Universo Paralelo',
  'Fue lo mejor del amor',
  'Que tal',
  'Ocho Cuarenta',
  'Intento',
  'Adicto a ti',
  'Beso a beso',
  'Quien se ha tomado todo el vino',
  'Hoy',
  'CaraLuna',
  'La tortura',
  'Despacito',
  'Robarte un beso',
  'Paisaje',
  'Arráncamelo',
  'Amores como el nuestro',
  'Llamado de emergencia',
  'Ella me levantó',
  'Abusadora',
  'Pobre Diabla',
  'Dale don dale',
  'Corazón Partío',
  'Amiga mía',
  'Corazón en la maleta',
  'Bendita tu luz',
  'Yendo a la casa de Damián',
  'Demoliendo hoteles',
  'Rezo por vos',
];
